prueba:
  test: ${password}
spring:
  application.name: foodcourt
  cloud:
    aws:
      region:
        static: us-east-1  # Cambia por la región de tu AWS
      secretsmanager:
        enabled: true      # Habilita el uso de Secrets Manager
        name: prod/secrets/database-secrets
  datasource:
    schema: foods_scheme
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: jdbc-secretsmanager:postgresql://${RDS_HOST}:5432/foods?useSSL=false&useTimezone=true&serverTimezone=UTC&currentSchema=foods_scheme
    username: prod/secrets/database-secrets
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        default_schema: foods_scheme
        dialect: org.hibernate.dialect.PostgreSQLDialect